### ISSUE TITLE
Missing hypervisor image rust-monitor-intel

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/atc22-ae#5]
Hai。
When I tried to Launch RustMonitor, it shows exception as follows:

`xxx@xxx-2288H-V6:~/atc22-ae/host$ ./launch_hyperenclave.sh binaries/rust_monitor_sme.elf binaries/hyper_enclave_5.3.0-050300-generic.ko`
> dev.hyper_enclave.enabled = 0
> sysctl: setting key "dev.hyper_enclave.enabled": 没有那个文件或目录

dmesg show error as follows:
> hyperenclave: Missing hypervisor image rust-monitor-intel

kernel info:
`xxx@xxx-2288H-V6:~/atc22-ae/host$ uname -r`
> 5.3.0-050300-generic

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , it seems that you try to run the HyperEnclave AE project on Intel platform.

As shown in the [README.md](https://github.com/HyperEnclave/atc22-ae?tab=readme-ov-file#2-system-requirements), we may need to run it on AMD platform:

> -  Hardware:
A 64-bit AMD platform with SVM (Secure Virtual Machine). Optionally, we recommend that the platform should support SME (Secure Memory Encryption) for the protection against physical memory attacks.
......

**Comment by Ariel08081214** [comment]
Thanks for your reply. But how can I reproduce reports's experiments on intel CPU as I have not AMD CPU？@Bonjourz

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , as stated in the "Section 7 Evaluation" in HyperEnclave [paper](https://www.usenix.org/system/files/atc22-jia-yuekai.pdf): 

> We deployed HyperEnclave on a server with two AMD EPYC 7601 CPUs (2 threads per core, total of 128 logical cores) with 512 GB DDR4 RAM. We configure 2 GB reserved memory for RustMonitor, and 24 GB for EPC memory. The primary OS is Ubuntu 18.04 LTS with Linux kernel 4.19.91. For comparison, we run the same experiments on an Intel Xeon E31270 v6 CPU with SGX enabled, with 64 GB DDR4 RAM, running the same OS. The SGX SDK version for both HyperEnclave and the native SGX hardware are 2.13. All programs are compiled with GCC 7.5.0 and the same optimization level.

we only evaluate HyperEnclave on AMD platform. 

Currently, we only provide  deployment instructions on artifact evaluation for AMD SME platform.

**Comment by Ariel08081214** [comment]
@Bonjourz Well, I got it, thanks again

**Comment by Ariel08081214** [comment]
@Bonjourz hai，how does the application run on AMD platform by occlum？ the official shows that occlum is for intel SGX. It confuses me

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , 
> the official shows that occlum is for intel SGX

Native Occlum is target on Intel platform and SGX ISA. 

> how does the application run on AMD platform by occlum？

For HyperEnclave, Occlum needs to be extended. HyperEnclave ISA is similar to SGX ISA, so such extension only entail relative minimal changes.

**Comment by Ariel08081214** [comment]
thanks for your reply. It means that applications can run on HYGON cpu or AMD CPU by hyperenclave occlum without modification as occlum has been extended？am I right？ @Bonjourz

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , 

> It means that applications can run on HYGON cpu or AMD CPU by hyperenclave occlum without modification as occlum has been extended？

It has been discussed here:
https://github.com/HyperEnclave/hyperenclave/issues/20#issuecomment-2334128227

Such issue is has been resolved. Close it. 

If you want to discuss some other topics, you need to open another issue discussion.
